# THIS IS A TEMPLATE
# PLEASE RENAME THIS FILE TO "config.yaml"
# PLEASE REPLACE ALL TEXT IN ALL CAPS WITH THE REQUIRED INFORMATION
# ENTER EXACTLY AS YOU WOULD IN TO LOG IN USING OTHER SOFTWARE
# FOR PATHS DO NOT ESCAPE WINDOWS PATHS,
# EXAMPLE: C:\PATH\TO\LOGS\ ... NOT C:\\PATH\\TO\\LOG

# SQL database connection configuration
db:
  server: SQL SERVER ADDRESS
  table: SQL TABLE FOR RFID
  user: SQL SERVER LOGIN USER
  pass: SQL SERVER LOGIN PASSWORD
